### ISSUE TITLE
broken feather icons

### ISSUE THREAD

**Issue by JustinVoitel** [Introvertuous/svelte-icons#8]
As seen on [https://www.svelte-icons.gibdig.com/](url), the complete feather-icon-set is displayed wrong.
Possible solutions might be:
- setting `stroke-width`
- setting `fill` to none

..only for this set

Also the majority of `d` attributes of the `path` tags are set to "undefined"

**Comment by JaySwaan** [comment]
It looks like this problem is deeper than just setting attributes, the reason d is undefined is because the Feather set is being imported from node modules which works fine for some other sets, but Feather is not built like other icon sets. For most Feather icons they are using different tags than just path like polyline, circle, line so naturally the d attribute is undefined since these other tags don't use path commands.

This project only returns a path and doesn't anticipate other tags:
```
const svgContent = child
  .map(({ attr }) => {
    const { d } = attr;
    return `<path d="${d}" />`;
  })
  .join('\n');
```

The only fix would be to write an entirely different set of rules in build.ts for reading and displaying Feather Icons, or to make an alternate set of Feather Icons by running them through SVGOMG or editing in Inkscape or Illustrator to expand the strokes so they have a consistent path tag. Other than that I think Feather should be removed, it's non-standard and needs it's own Svelte-based project.

**Comment by gibdig** [comment]
I will look into this soon, I don't think excluding an icon set is a good solution, even if there is changes needed to the build step, the project is meant to be a collection of icon sets.

**Comment by gibdig** [comment]
I will however remove them for the time being and will keep this issue open to track an enhancement. 

https://github.com/gibdig/svelte-icons/commit/4dc686c9db8b18d35bef2706b1374b43c7b85aa4
